services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    volumes:
      - kfc-db:/app/server/db

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_HOST=auth-service
      - AUTH_PORT=8000
      - REDIS_HOST=redis
    depends_on:
      - auth-service
      - redis

  kfc-server:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - kfc-db:/app/server/db
    environment:
      - REDIS_HOST=redis
      - AUTH_HOST=auth-service
      - AUTH_PORT=8000
    depends_on:
      - redis
      - auth-service
      - api-gateway

volumes:
  kfc-db:
