services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    volumes:
      - kfc-db:/app/server/db

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_HOST=auth-service
      - AUTH_PORT=8000
      - REDIS_HOST=redis
    depends_on:
      - auth-service
      - redis

  rooms-api:
    build:
      context: .
      dockerfile: rooms-api/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  rating-service:
    build:
      context: .
      dockerfile: rating-service/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - kfc-db:/app/server/db

  kfc-server:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - kfc-db:/app/server/db
    environment:
      - REDIS_HOST=redis
      - AUTH_HOST=auth-service
      - AUTH_PORT=8000
      - ROOMS_HOST=rooms-api
      - ROOMS_PORT=8001
      - RATING_HOST=rating-service
      - RATING_PORT=8002
    depends_on:
      - redis
      - auth-service
      - api-gateway
      - rooms-api
      - rating-service

volumes:
  kfc-db:
